// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/book/:bookId": {
    params: {
      "bookId": string;
    };
  };
  "/rank": {
    params: {};
  };
  "/read/:bookId/:chapterId": {
    params: {
      "bookId": string;
      "chapterId": string;
    };
  };
  "/category/:categoryId": {
    params: {
      "categoryId": string;
    };
  };
  "/author/:authorId": {
    params: {
      "authorId": string;
    };
  };
  "/special/:type": {
    params: {
      "type": string;
    };
  };
  "/upload": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/book/:bookId" | "/rank" | "/read/:bookId/:chapterId" | "/category/:categoryId" | "/author/:authorId" | "/special/:type" | "/upload" | "/*";
  };
  "routes/home/index.tsx": {
    id: "routes/home/index";
    page: "/";
  };
  "routes/book/index.tsx": {
    id: "routes/book/index";
    page: "/book/:bookId";
  };
  "routes/rank/index.tsx": {
    id: "routes/rank/index";
    page: "/rank";
  };
  "routes/read/index.tsx": {
    id: "routes/read/index";
    page: "/read/:bookId/:chapterId";
  };
  "routes/category/index.tsx": {
    id: "routes/category/index";
    page: "/category/:categoryId";
  };
  "routes/author/index.tsx": {
    id: "routes/author/index";
    page: "/author/:authorId";
  };
  "routes/special/index.tsx": {
    id: "routes/special/index";
    page: "/special/:type";
  };
  "routes/upload/index.tsx": {
    id: "routes/upload/index";
    page: "/upload";
  };
  "routes/not-found.tsx": {
    id: "routes/not-found";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home/index": typeof import("./app/routes/home/index.tsx");
  "routes/book/index": typeof import("./app/routes/book/index.tsx");
  "routes/rank/index": typeof import("./app/routes/rank/index.tsx");
  "routes/read/index": typeof import("./app/routes/read/index.tsx");
  "routes/category/index": typeof import("./app/routes/category/index.tsx");
  "routes/author/index": typeof import("./app/routes/author/index.tsx");
  "routes/special/index": typeof import("./app/routes/special/index.tsx");
  "routes/upload/index": typeof import("./app/routes/upload/index.tsx");
  "routes/not-found": typeof import("./app/routes/not-found.tsx");
};